create table public.workitems (
    id          integer  generated by default as identity primary key,
    title       text     not null,
    type        smallint not null check (type in (0, 1)),           -- WorkItemType: 0 = Bug, 1 = Feature
    status      smallint not null check (status between 0 and 2),   -- WorkItemStatus: 0 = New, 1 = In Progress, 2 = Done
    project_id  bigint   not null,                                  -- GitHub repository id
    "order"     integer  not null                                   -- "order" is a reserved word, keep it quoted
);

alter table public.workitems enable row level security;

create policy "Allow anon full access to workitems"
    on public.workitems
    for all
    to anon
    using (true)
    with check (true);
